version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server
    depends_on:
      - postgresql
      - mosquitto
    networks:
      - lora

  chirpstack-application-server:
    image: knot-chirpstack-app:latest
    container_name: knot-chirpstack-app
    ports:
      - 8080:8080
    volumes:
      - ./configuration/knot:/etc/knot
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - chirpstack-network-server
    networks:
      - lora

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on: 
      - mosquitto
    networks:
      - lora

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    networks:
      - lora

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data
    networks:
      - lora

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
    volumes: 
      - ./configuration/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - lora

volumes:
  postgresqldata:
  redisdata:

networks:
  lora:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.52.0.0/16