# See https://www.chirpstack.io/application-server/install/config/ for a full
# configuration example and documentation.

[postgresql]
dsn="postgres://chirpstack_as:chirpstack_as@postgresql/chirpstack_as?sslmode=disable"

[redis]
url="redis://redis:6379"

[application_server.integration]
enabled = ["knot"]

[application_server.integration.knot]
url = "amqp://knot:knot@192.168.43.196:5672"
name = "knot lora"
user_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODE5Mjk3NzAsImp0aSI6IjM2MmI0ODRhLWY3NjYtNGVmNy1hMzk5LWZkOGIyZWUyZDc4ZCIsImlhdCI6MTY1MDM5Mzc3MCwiaXNzIjoibHVpc2ZlbGlwODBAZ21haWwuY29tIiwidHlwZSI6Mn0.AbzL31JdXgl8RX8eqWrnnmZK7eNYhlMWvbDAQmDAgnU"

[[application_server.integration.knot.devices]]
deveui  = "f803320600027594"
token   = ""
name    = "lora"

[[application_server.integration.knot.devices.config]]
sensorId = 1

[application_server.integration.knot.devices.config.schema]
valueType = 2
unit      = 0
typeId    = 65296
name      = "sensor_teste"

[application_server.integration.knot.devices.config.event]
change = true
timeSec = 12

[application_server.api]
public_host="chirpstack-application-server:8001"

[application_server.external_api]
bind="0.0.0.0:8080"
jwt_secret="verysecret"
