# See https://www.chirpstack.io/application-server/install/config/ for a full
# configuration example and documentation.

[postgresql]
dsn="postgres://chirpstack_as:chirpstack_as@postgresql/chirpstack_as?sslmode=disable"

[redis]
url="redis://redis:6379"

[application_server.integration]
enabled = ["knot"]

[application_server.integration.knot]
url = "amqp://knot:knot@172.25.4.125:5672"
name = "knot lora"
user_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODQ1OTE1MzMsImp0aSI6IjYxNWY5OWFkLThhOTktNGFhYy05YmIxLTMzY2NhYzc0YWVjNCIsImlhdCI6MTY1MzA1NTUzMywiaXNzIjoiY2VzYXJhaGZvZ0Brbm90Lm9yZy5iciIsInR5cGUiOjJ9.nzQsCU09iW8W6XS29SS5UVDzwZQkb9qfSsyRFEh0-Rg"


[[application_server.integration.knot.devices]]
id      = "c3dbe3f250dd2678"
token   = ""
name    = "lora"

[[application_server.integration.knot.devices.config]]
sensorId = 33605

[application_server.integration.knot.devices.config.schema]
valueType = 2
unit      = 1
typeId    = 65296
name      = "Hora_da_Temperatura_Máx"

[application_server.integration.knot.devices.config.event]
change = true
timeSec = 12

[[application_server.integration.knot.devices.config]]
sensorId = 34563

[application_server.integration.knot.devices.config.schema]
valueType = 2
unit      = 1
typeId    = 65296
name      = "sensor_umidade"

[application_server.integration.knot.devices.config.event]
change = true
timeSec = 12


[application_server.api]
public_host="chirpstack-application-server:8001"

[application_server.external_api]
bind="0.0.0.0:8080"
jwt_secret="verysecret"
